# Cloud Build configuration file for the Malware Detonation Platform
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/malware-detonation-platform:$COMMIT_SHA', '.']
    timeout: '1200s'  # 20 minutes to allow for potential slow builds

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/malware-detonation-platform:$COMMIT_SHA']

  # Create service account if it doesn't exist
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud iam service-accounts describe malware-platform-sa@$PROJECT_ID.iam.gserviceaccount.com || \
        gcloud iam service-accounts create malware-platform-sa \
          --display-name="Malware Detonation Platform Service Account"

  # Grant necessary permissions to the service account
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        for role in roles/storage.admin roles/pubsub.editor roles/compute.admin roles/secretmanager.secretAccessor; do
          gcloud projects add-iam-policy-binding $PROJECT_ID \
            --member="serviceAccount:malware-platform-sa@$PROJECT_ID.iam.gserviceaccount.com" \
            --role="$$role" || echo "Already has $$role"
        done

  # Setup required GCP resources
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Create Pub/Sub topics and subscriptions
        gcloud pubsub topics create detonation-notifications --project=$PROJECT_ID || true
        gcloud pubsub subscriptions create detonation-app-sub --topic=detonation-notifications --project=$PROJECT_ID || true
        
        # Create storage buckets
        gsutil mb -l ${_REGION} gs://malware-samples-$PROJECT_ID || true
        gsutil mb -l ${_REGION} gs://detonation-results-$PROJECT_ID || true
        
        # Create Secret Manager secret for app key if it doesn't exist
        SECRET_EXISTS=$(gcloud secrets list --filter="name:malware-platform-secrets" --format="value(name)" | wc -l)
        if [ $SECRET_EXISTS -eq 0 ]; then
          echo "Creating secret..."
          echo -n "$(openssl rand -base64 32)" | gcloud secrets create malware-platform-secrets --data-file=-
          gcloud secrets add-iam-policy-binding malware-platform-secrets \
            --member="serviceAccount:malware-platform-sa@$PROJECT_ID.iam.gserviceaccount.com" \
            --role="roles/secretmanager.secretAccessor"
        fi

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'malware-detonation-platform'
      - '--image=gcr.io/$PROJECT_ID/malware-detonation-platform:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--service-account=malware-platform-sa@$PROJECT_ID.iam.gserviceaccount.com'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--set-env-vars=GCP_PROJECT_ID=$PROJECT_ID,GCP_REGION=${_REGION},GCP_ZONE=${_REGION}-a,GCP_STORAGE_BUCKET=malware-samples-$PROJECT_ID,GCP_RESULTS_BUCKET=detonation-results-$PROJECT_ID,APP_NAME=Malware Detonation Platform,DEBUG=false'
      - '--set-secrets=SECRET_KEY=malware-platform-secrets:latest'

# Fix for the service account and logging issue
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # More powerful machine for faster builds

# Tag the produced images
images:
  - 'gcr.io/$PROJECT_ID/malware-detonation-platform:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/malware-detonation-platform:latest'

# Default substitution values
substitutions:
  _REGION: us-central1

# Maximum build timeout
timeout: '1800s'  # 30 minutes total
