# Cloud Build configuration file for the Malware Detonation Platform
steps:
  # Set up permissions for Cloud Build service account
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'setup-build-permissions'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Setting up Cloud Build permissions..."
        
        # Get the Cloud Build service account email
        PROJECT_NUMBER=$(gcloud projects describe $PROJECT_ID --format='value(projectNumber)')
        CLOUDBUILD_SA="${PROJECT_NUMBER}@cloudbuild.gserviceaccount.com"
        
        # Grant Artifact Registry permissions
        gcloud projects add-iam-policy-binding $PROJECT_ID \
          --member="serviceAccount:${CLOUDBUILD_SA}" \
          --role="roles/artifactregistry.writer" > /dev/null 2>&1 || echo "Failed to grant Artifact Registry permissions"
        
        # Grant Storage Admin permissions (for Container Registry)
        gcloud projects add-iam-policy-binding $PROJECT_ID \
          --member="serviceAccount:${CLOUDBUILD_SA}" \
          --role="roles/storage.admin" > /dev/null 2>&1 || echo "Failed to grant Storage permissions"
        
        echo "Cloud Build permissions setup complete"

  # Setup infrastructure before build
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'infrastructure-setup'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Setting up required infrastructure..."
        
        # Create required storage buckets
        echo "Creating storage buckets..."
        gsutil mb -l ${_REGION} gs://malware-samples-$PROJECT_ID 2>/dev/null || echo "Bucket already exists"
        gsutil mb -l ${_REGION} gs://detonation-results-$PROJECT_ID 2>/dev/null || echo "Bucket already exists"
        
        # Create Pub/Sub topic and subscription for notifications
        echo "Setting up Pub/Sub..."
        gcloud pubsub topics create detonation-notifications 2>/dev/null || echo "Topic already exists"
        gcloud pubsub subscriptions create detonation-app-sub --topic=detonation-notifications 2>/dev/null || echo "Subscription already exists"
        
        # Create service account if it doesn't exist
        echo "Setting up service account..."
        # Direct check without variable assignment
        if ! gcloud iam service-accounts list --filter="email:malware-platform-sa@$PROJECT_ID.iam.gserviceaccount.com" --format="value(email)" | grep -q malware-platform-sa; then
          echo "Creating service account malware-platform-sa..."
          gcloud iam service-accounts create malware-platform-sa \
            --display-name="Malware Detonation Platform Service Account" || echo "Failed to create service account, may already exist"
        else
          echo "Service account malware-platform-sa already exists"
        fi
        
        # Grant IAM roles individually without --condition flag
        echo "Granting roles to service account..."
        
        # Storage Admin role
        echo "Granting Storage Admin role..."
        gcloud projects add-iam-policy-binding $PROJECT_ID \
          --member="serviceAccount:malware-platform-sa@$PROJECT_ID.iam.gserviceaccount.com" \
          --role="roles/storage.admin" > /dev/null 2>&1 || echo "Role binding for Storage Admin failed or already exists"
        
        # Pub/Sub Publisher role
        echo "Granting Pub/Sub Publisher role..."
        gcloud projects add-iam-policy-binding $PROJECT_ID \
          --member="serviceAccount:malware-platform-sa@$PROJECT_ID.iam.gserviceaccount.com" \
          --role="roles/pubsub.publisher" > /dev/null 2>&1 || echo "Role binding for Pub/Sub Publisher failed or already exists"
        
        # Pub/Sub Subscriber role
        echo "Granting Pub/Sub Subscriber role..."
        gcloud projects add-iam-policy-binding $PROJECT_ID \
          --member="serviceAccount:malware-platform-sa@$PROJECT_ID.iam.gserviceaccount.com" \
          --role="roles/pubsub.subscriber" > /dev/null 2>&1 || echo "Role binding for Pub/Sub Subscriber failed or already exists"
        
        # Logs Writer role
        echo "Granting Logs Writer role..."
        gcloud projects add-iam-policy-binding $PROJECT_ID \
          --member="serviceAccount:malware-platform-sa@$PROJECT_ID.iam.gserviceaccount.com" \
          --role="roles/logging.logWriter" > /dev/null 2>&1 || echo "Role binding for Logs Writer failed or already exists"
        
        # Cloud Run Admin role
        echo "Granting Cloud Run Admin role..."
        gcloud projects add-iam-policy-binding $PROJECT_ID \
          --member="serviceAccount:malware-platform-sa@$PROJECT_ID.iam.gserviceaccount.com" \
          --role="roles/run.admin" > /dev/null 2>&1 || echo "Role binding for Cloud Run Admin failed or already exists"
        
        # Compute Admin role
        echo "Granting Compute Admin role..."
        gcloud projects add-iam-policy-binding $PROJECT_ID \
          --member="serviceAccount:malware-platform-sa@$PROJECT_ID.iam.gserviceaccount.com" \
          --role="roles/compute.admin" > /dev/null 2>&1 || echo "Role binding for Compute Admin failed or already exists"
        
        # Secret Manager Secret Accessor role
        echo "Granting Secret Manager Secret Accessor role..."
        gcloud projects add-iam-policy-binding $PROJECT_ID \
          --member="serviceAccount:malware-platform-sa@$PROJECT_ID.iam.gserviceaccount.com" \
          --role="roles/secretmanager.secretAccessor" > /dev/null 2>&1 || echo "Role binding for Secret Manager Secret Accessor failed or already exists"
        
        echo "Infrastructure setup complete"

  # Build the Docker image with extended timeout for large builds
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/malware-detonation-platform:$COMMIT_SHA', '.']
    timeout: '1800s'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-sha-image'
    args: ['push', 'gcr.io/$PROJECT_ID/malware-detonation-platform:$COMMIT_SHA']

  # Deploy to Cloud Run using cloudrun.yaml configuration
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying to Cloud Run..."
        
        # First, verify the cloudrun.yaml file exists
        if [ ! -f cloudrun.yaml ]; then
          echo "Error: cloudrun.yaml not found!"
          exit 1
        fi
        
        # Process the cloudrun.yaml file with necessary substitutions and fix for fieldRef
        cat cloudrun.yaml | \
        sed "s/\$PROJECT_ID/$PROJECT_ID/g" | \
        sed "s/\$COMMIT_SHA/$COMMIT_SHA/g" | \
        # Fix the fieldRef in env var to use proper metadata.annotations format
        sed "s/fieldRef:/value: \"${_REGION}\"/g" > processed_cloudrun.yaml
        
        echo "Substitutions applied to cloudrun.yaml"
        
        # Deploy using the processed YAML file
        echo "Deploying service to Cloud Run..."
        gcloud run services replace processed_cloudrun.yaml \
          --platform=managed \
          --region=${_REGION}
        
        # Allow public access if needed - fixed command without --condition flag
        echo "Configuring public access..."
        gcloud run services add-iam-policy-binding malware-detonation-platform \
          --member="allUsers" \
          --role="roles/run.invoker" \
          --region=${_REGION}
          
        echo "Deployment to Cloud Run complete"

  # Tag the image as latest for future reference
  - name: 'gcr.io/cloud-builders/docker'
    id: 'tag-latest'
    args: ['tag', 'gcr.io/$PROJECT_ID/malware-detonation-platform:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/malware-detonation-platform:latest']

  # Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args: ['push', 'gcr.io/$PROJECT_ID/malware-detonation-platform:latest']

  # Verify deployment success - ultra simplified to avoid ANY variable assignments
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'verify-deployment'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Verifying deployment..."
        
        # Wait a moment for deployment to stabilize
        sleep 10
        
        # Get service URL and print directly - no variables
        echo "Service URL Info:"
        gcloud run services describe malware-detonation-platform --region=${_REGION} --format='value(status.url)' 2>/dev/null || echo "Service URL not available"
        
        # No health check to avoid variables
        echo "Deployment verification complete"
        
        # Final deployment message
        echo "====================================="
        echo "Deployment complete!"
        echo "====================================="

# Configuration options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # More powerful machine for faster builds
  dynamicSubstitutions: true

# Images to push
images:
  - 'gcr.io/$PROJECT_ID/malware-detonation-platform:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/malware-detonation-platform:latest'

# Default substitution values
substitutions:
  _REGION: us-central1

# Extended build timeout (60 minutes)
timeout: '3600s'
