apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: malware-detonation-platform
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "5"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/startup-probe-period-seconds: "60"
        run.googleapis.com/liveness-probe-period-seconds: "30"
    spec:
      serviceAccountName: malware-platform-sa@${PROJECT_ID}.iam.gserviceaccount.com
      containers:
      - image: gcr.io/${PROJECT_ID}/malware-detonation-platform:latest
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1" 
            memory: "1Gi"
        env:
          - name: DEBUG
            value: "false"
          - name: GCP_PROJECT_ID
            value: "${PROJECT_ID}"
          - name: GCP_STORAGE_BUCKET
            value: "malware-samples-${PROJECT_ID}"
          - name: GCP_RESULTS_BUCKET
            value: "detonation-results-${PROJECT_ID}"
          - name: GCP_REGION
            value: "us-central1"
          - name: GCP_ZONE
            value: "us-central1-a"
          - name: VM_NETWORK
            value: "detonation-network"
          - name: VM_SUBNET
            value: "detonation-subnet"
          - name: GENERATE_TEMPLATES
            value: "false"
          - name: GUNICORN_WORKERS
            value: "1"
          - name: GUNICORN_TIMEOUT
            value: "300"
          - name: DB_POOL_SIZE
            value: "5"
          - name: MAX_CONCURRENT_DETONATIONS
            value: "3"
          - name: SECRET_KEY
            value: "production-secret-key-${PROJECT_ID}"
          - name: DATABASE_PATH
            value: "/app/data/malware_platform.db"
          - name: MAX_UPLOAD_SIZE_MB
            value: "100"
          - name: APP_NAME
            value: "Malware Detonation Platform"
        ports:
          - containerPort: 8080
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 4
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 4
