# Render deployment configuration for HuntCraft (Free Tier)
services:
  - type: web
    name: huntcraft-web
    runtime: python
    plan: free
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      echo "Build completed successfully"
    startCommand: gunicorn "main:create_app()" -b 0.0.0.0:$PORT -w 2 --timeout 120
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.0"
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: APP_NAME
        value: "HuntCraft"
      - key: PRIMARY_COLOR
        value: "#4a6fa5"
      - key: SECONDARY_COLOR
        value: "#6c757d"
      - key: DANGER_COLOR
        value: "#dc3545"
      - key: SUCCESS_COLOR
        value: "#28a745"
      - key: WARNING_COLOR
        value: "#ffc107"
      - key: INFO_COLOR
        value: "#17a2b8"
      - key: DARK_COLOR
        value: "#343a40"
      - key: LIGHT_COLOR
        value: "#f8f9fa"
      - key: MAX_UPLOAD_SIZE_MB
        value: "16"
      - key: ENABLE_ADVANCED_ANALYSIS
        value: "true"
      - key: ENABLE_DATA_EXPORT
        value: "true"
      - key: ENABLE_VISUALIZATION
        value: "true"
      - key: LOG_LEVEL
        value: "INFO"
      - key: RENDER_SERVICE
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: huntcraft-db
          property: connectionString

databases:
  - name: huntcraft-db
    plan: free
    databaseName: huntcraft
    user: huntcraft_user
    ipAllowList:
      - source: 0.0.0.0/0
        description: All services
