# Render deployment configuration for Threat Hunting Workbench
services:
  - type: web
    name: threat-hunting-workbench
    env: python
    region: oregon
    plan: free

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p data/uploads
      echo "Build completed successfully"

    startCommand: gunicorn "main:create_app()" -b 0.0.0.0:$PORT -w 2 --timeout 120

    autoDeploy: true
    healthCheckPath: /health

    envVars:
      - key: PYTHON_VERSION
        value: "3.9.0"
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: APP_NAME
        value: "Threat Hunting Workbench"
      - key: PRIMARY_COLOR
        value: "#4a6fa5"
      - key: SECONDARY_COLOR
        value: "#6c757d"
      - key: DANGER_COLOR
        value: "#dc3545"
      - key: SUCCESS_COLOR
        value: "#28a745"
      - key: WARNING_COLOR
        value: "#ffc107"
      - key: INFO_COLOR
        value: "#17a2b8"
      - key: DARK_COLOR
        value: "#343a40"
      - key: LIGHT_COLOR
        value: "#f8f9fa"
      - key: MAX_UPLOAD_SIZE_MB
        value: "16"
      - key: ENABLE_ADVANCED_ANALYSIS
        value: "true"
      - key: ENABLE_DATA_EXPORT
        value: "true"
      - key: ENABLE_VISUALIZATION
        value: "true"
      - key: LOG_LEVEL
        value: "INFO"
      - key: DATABASE_PATH
        value: "/opt/render/project/src/data/threat_hunting.db"
      - key: UPLOAD_FOLDER
        value: "/opt/render/project/src/data/uploads"

    disk:
      name: threat-hunting-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1

    services:
      - type: worker
        name: cleanup-uploads
        schedule: "0 0 * * *"
        command: "find /opt/render/project/src/data/uploads -type f -mtime +30 -delete"

    healthCheck:
      healthyThreshold: 3
      unhealthyThreshold: 3
      path: /health
      timeout: 10
      interval: 60
      retries: 3
